name: Build and Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x and build
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      run: npm install
      run: npm run build --if-present
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to S3 with the AWS CLI
      run: aws s3 sync build/ s3://react-playground

    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id EEHHYR0L1LJH1 --paths "*"


